const config = {
	word_example: [
		"All their equipment and instruments are alive.",
		"A red flare silhouetted the jagged edge of a wing.",
		"I watched the storm, so beautiful yet terrific.",
		"Almost before we knew it, we had left the ground.",
		"A shining crescent far beneath the flying vessel.",
		"It was going to be a lonely trip back.",
		"Mist enveloped the ship three hours out from port.",
		"My two natures had memory in common.",
		"Silver mist suffused the deck of the ship.",
		"The face of the moon was in shadow.",
		"She stared through the window at the stars.",
		"The recorded voice scratched in the speaker.",
		"The sky was cloudless and of a deep dark blue.",
		"The spectacle before us was indeed sublime.",
		"Then came the night of the first falling star.",
		"Waves flung themselves at the blue evening.",
	],
	categories: [
		'Serif',
		'Sans Serif',
		'Display',
		'Handwriting',
		'Monospace'
	],
	sorting: [
		{value: 'trending', title:'Trending'},
		{value: 'popularity',title:'Popular'},
		{value: 'dateAdded',title:'Date Added'},
		{value: 'family', title:'Alphabetical'}
	],
	languages: [
		'Arabic',
		'Bengali',
		'Cyrillic',
		'Cyrillic Extended',
		'Devanagari',
		'Greek',
		'Greek Extended',
		'Gujarati',
		'Gurmukhi',
		'Hebrew',
		'Japanese',
		'Kannada',
		'Khmer',
		'Korean',
		'Latin',
		'Latin Extended',
		'Malayalam',
		'Myanmar',
		'Oriya',
		'Sinhala',
		'Tamil',
		'Telugu',
		'Thai',
		'Vietnamese'
	],
}

export default config;